#config for training
num_epochs: 1000
lr: 0.0001
lr_scheduler: false
weight_decay: 0.01
bottleneck:
  process: mul
checkpoint_dir: '/home/workspace/yoavellinson/mono-to-stereo/checkpoints_slurm_2db'
gen_loss: false
dataset:
  fs: 16000
  csv_path: '/dsi/gannot-lab1/datasets/whamr/data/mix_2_spk_filenames_tr.csv'
  test_csv_path: '/dsi/gannot-lab1/datasets/whamr/data/mix_2_spk_filenames_tt.csv'
  time_len: 5.115 #seconds, has to be it to match 640 stft fframes
  batch_size_train: 16 #5
  batch_size_val: 5
  num_workers: 32
  norm_sample: True
  n_channels: 2
  hrtf_path: '/home/workspace/yoavellinson/guided_extraction/hrtf_sofa/RIEC_hrir_subject_001.sofa'
  h_anechoic_path: '/home/workspace/yoavellinson/extraction_master/complex_nn/extraction/reverberation_simulator/h_anechoic'
  var_hrtf: 10 #recive the hrtf of +-10 deg
  noise_dir: '/home/workspace/yoavellinson/extraction_master/complex_nn/extraction/anechoic-noise/output'
  noise_tol: 10
  n_freqs: 256
  db_root_train: '/dsi/gannot-lab1/datasets/whamr/wav16k/min/tr/mix_both_reverb'
  db_root_test: '/dsi/gannot-lab1/datasets/whamr/wav16k/min/tt/mix_both_reverb'
  wsj0_root: '/dsi/gannot-lab1/datasets/wsj0_root/'
  array:
    d: 0.03 #m
    n: 7
    r: 1.5
    c: 343.0
    room_x: 6
    room_y: 2.8
    room_z: 5
output_channels: 7
stft:
  fft_length: 512
  fft_hop: 128
lcmv:
  theta_target: 45
  theta_interf: -45
loss:
  emb_loss_factor: 1000
  ecapa2:
    path: '/home/workspace/yoavellinson/mono-to-stereo/ecapa2/ecapa2.pt'
ncsnpp:
    hrtf_channels: 28 #N channels * RealImagenery (2) * number of responses, for two responses do N*4
    ch_mult: [1, 1, 2, 2, 2, 2, 2]
    num_of_res_blocks: 2
    unet_in_channels: 128
    act: swish
    dropout: 0
    fir: True
    fir_kernel: [1, 3, 3, 1]
    init_scale: 0
    skip_rescale: True
    combine_method: sum
    attn_resolutions: 16
    image_size: 256
    fourier_scale: 16
    resamp_with_conv: True
    loss_type: mse
    t_embed_dim: 512
    gaussian_fourier_projection: 96
    gfp_layers: 5
    t_eps: 0.03
    t_rev: 1.0
    alpha: 0.5
    beta: 0.15
    ode:
      sigma_min: 1e-3
      sigma_max: 1.0
      N: 30
    bottleneck_only_guidence: false
    botteleneck_temb: True
    ema_dacay: 0.999
