project: 'binaural_NBSS'

model:
  inputchannels: 1
  num_filters: 64
  kernel_size: 4
  norm: layer
  act_fun: relu
  ref_channel: 0
  output_channels: 2
  n_channel: 2
  n_layers: 6 # 12 for large
  dim_hidden: 96 # 192 for large
  dim_ffn: 192  # 384 for large
  block:
    n_heads: 2
    dropout: 0
    conv_kernel_size: 3
    n_conv_groups: 8
    norms: ["LN", "GBN", "GBN"]
    group_batch_norm: 
      group_size: 257
      share_along_sequence_dim: False

stft:
  fs: 16000
  fft_length: 512
  fft_hop: 128
  window: hann

dataset:
  sofas_ppath: '/home/workspace/yoavellinson/binaural_TSE_Gen/pts'
  train_csv_path: '/home/workspace/yoavellinson/binaural_TSE_Gen/csvs/HRTF_train_VAE_wsj0_10k_mp.csv'
  test_csv_path: '/home/workspace/yoavellinson/binaural_TSE_Gen/csvs/HRTF_test_VAE_wsj0_1k_mp.csv'
  norm_sample: True
  time_len: 5
  n_channels: 2

loss:
  sisdr_coeff: 0.5
  mae_coeff: 10
  pesq_coeff: 0.5

training:
  num_epochs: 1000
  lr: 1e-3
  batch_size: 4
  num_workers: 4
  weight_decay: 0.05
  seed: 42
  checkpoint_dir: '/home/workspace/yoavellinson/binaural_TSE_Gen/checkpoints/binaural_NBSS'
