project: 'binaural_NBSS_multi_to_narrow_band'
checkpoint_path: '/home/workspace/yoavellinson/binaural_TSE_Gen/checkpoints/binaural_NBSS_large_mel2'
model:
  inputchannels: 1
  num_filters: 64
  kernel_size: 4
  norm: layer
  act_fun: relu
  ref_channel: 0
  output_channels: 2
  n_channel: 2
  n_layers_mels: 4 # 12 for large
  n_layers_shared: 4
  dim_hidden: 96 # 192 for large
  dim_ffn: 192  # 384 for large
  num_bins: 6
  block:
    n_heads: 2
    dropout: 0
    conv_kernel_size: 3
    n_conv_groups: 8
    norms: ["LN", "GBN", "GBN"]
    group_batch_norm: 
      group_size: 257
      share_along_sequence_dim: False

stft:
  fs: 16000
  fft_length: 512
  fft_hop: 128
  window: hann

dataset:
  sofas_ppath: '/home/workspace/yoavellinson/binaural_TSE_Gen/pts'
  train_csv_path: '/home/workspace/yoavellinson/binaural_TSE_Gen/csvs/HRTF_train_VAE_wsj0_10k_mp_clean.csv'
  test_csv_path: '/home/workspace/yoavellinson/binaural_TSE_Gen/csvs/HRTF_test_VAE_wsj0_1k_mp.csv'
  norm_sample: True
  time_len: 3
  n_channels: 2

loss:
  sisdr_coeff: 0.5
  mae_coeff: 10
  pesq_coeff: 0.5

training:
  num_epochs: 1000
  lr: 1e-3
  batch_size: 5
  num_samples: 300
  b_m: 200
  num_workers: 4
  weight_decay: 0.05
  seed: 42
